apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-app-1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/krishnaveniganesan/argocd.git
    targetRevision: HEAD
    path: argo/argocd/my-app/app1
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: example-app
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
