apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-2
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: example-app
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argo/argocd/my-app/app2
    repoURL: https://github.com/krishnaveniganesan/argocd.git
    targetRevision: HEAD

