kind: PersistentVolume
apiVersion: v1
metadata:
   name: mysql-pv-0
spec: 
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/krish"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: mysql-pvc-0
spec:
   storageClassName: local-storage
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
        storage: 512Mi