apiVersion: v1
kind: Service
metadata:
  name: database-service
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
    nodeport: 30050
  selector:
    app: database
  type: NodePort
